version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - arbdata:/app/backend/prisma
    env_file:
      - .env
    restart: unless-stopped

volumes:
  arbdata:
